# Generated by Django 5.2.1 on 2025-05-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_social_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
    ]
