# Generated by Django 5.2.1 on 2025-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cloudinary_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Formats acceptés : MP3, WAV, M4A, OGG, WEBM', null=True, upload_to='temp_podcasts/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
