# Generated by Django 5.2.1 on 2025-05-27 08:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_podcast_cloudinary_public_id_podcast_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cloudinary_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_featured_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='cloudinary_image_large',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_featured_image_large'),
        ),
        migrations.AddField(
            model_name='post',
            name='cloudinary_image_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_featured_image_thumbnail'),
        ),
        migrations.AddField(
            model_name='post',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
