# Generated by Django 5.2.1 on 2025-05-27 08:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_cloudinary_image_post_cloudinary_image_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='is_published',
        ),
        migrations.AddField(
            model_name='podcast',
            name='cloudinary_cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='podcast_cover_image'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cloudinary_cover_image_large',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='podcast_cover_image_large'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cloudinary_cover_image_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='podcast_cover_image_thumbnail'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover_image_cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
