# Generated by Django 5.2.1 on 2025-05-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_podcast_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
