# Generated by Django 5.2.1 on 2025-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_podcast_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='transcript',
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en secondes', null=True),
        ),
    ]
