# Generated by Django 5.2.1 on 2025-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_video_transcript_alter_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='Courte description professionnelle', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text="Centres d'intérêt et compétences"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Si le profil est visible publiquement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
