# Generated by Django 4.2.11 on 2025-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_comment_content_alter_podcast_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, help_text='Description du podcast, peut contenir des liens et du texte enrichi', null=True),
        ),
    ]
